<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="192.168.1.10" failures="1" tests="7" name="webAutomation.portofolio.negative_case.Register" time="181.848" errors="0" timestamp="12 Jun 2022 09:50:24 GMT" skipped="0">
  <testcase classname="webAutomation.portofolio.negative_case.Register" name="register_user_with_exceed_character_maximum_first_name" time="21.636"/>
  <testcase classname="webAutomation.portofolio.negative_case.Register" name="register_user_without_check_terms_condition" time="19.431"/>
  <testcase classname="webAutomation.portofolio.negative_case.Register" name="register_user_with_registered_mail" time="20.848"/>
  <testcase classname="webAutomation.portofolio.negative_case.Register" name="register_user_with_telephone_below_minimum_characters" time="19.559"/>
  <testcase classname="webAutomation.portofolio.negative_case.Register" name="register_user_without_input_first_name" time="41.153"/>
  <testcase classname="webAutomation.portofolio.negative_case.Register" name="register_user_with_password_below_minimum_characters" time="39.684"/>
  <testcase classname="webAutomation.portofolio.negative_case.Register" name="register_user_with_different_confirm_password" time="19.537">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at webAutomation.portofolio.negative_case.Register.register_user_with_different_confirm_password(Register.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- register_user_with_different_confirm_password -->
</testsuite> <!-- webAutomation.portofolio.negative_case.Register -->
